run:
  timeout: 5m

# The list of linter based on the v1.64.5
# See the full list https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - grouper
    - iface
    - importas
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/example/repo
  dupl:
    threshold: 150
  funlen:
    lines: 120
    statements: 60
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 20
  cyclop:
    max-complexity: 20
    skip-tests: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  nestif:
    min-complexity: 4

issues:
  #new-from-rev: HEAD
  exclude-dirs:
    - tilt_modules
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - mnd
        - funlen
        - gocyclo
        - lll
        - err113
        - maintidx
        - ireturn
    - path: main\.go
      linters:
        - funlen
        - forbidigo
        - cyclop
